In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3],[2,4,6],[90,100,50]])
x

array([[  1,   2,   3],
       [  2,   4,   6],
       [ 90, 100,  50]])

In [3]:
np.amin(x)

1

In [4]:
np.amax(x)

100

In [5]:
np.amin(x,axis=1)

array([ 1,  2, 50])

In [6]:
np.amin(x,axis=0)

array([1, 2, 3])

In [7]:
np.amax(x,axis=1)

array([  3,   6, 100])

In [8]:
np.amax(x,axis=0)

array([ 90, 100,  50])

In [9]:
x

array([[  1,   2,   3],
       [  2,   4,   6],
       [ 90, 100,  50]])

In [10]:
np.average(x)

28.666666666666668

## Weighted Average

In [11]:
w = [1,2,3]

In [12]:
np.average(x, weights = w, axis = 0)

array([45.83333333, 51.66666667, 27.5       ])

In [13]:
np.average(x, weights = w,axis = 1)

array([ 2.33333333,  4.66666667, 73.33333333])

In [14]:
np.mean(x)

28.666666666666668

In [15]:
np.mean(x[0])

2.0

In [16]:
np.mean(x[1])

4.0

In [17]:
np.mean(x[2])

80.0

In [19]:
np.mean(x, axis = 0)

array([31.        , 35.33333333, 19.66666667])

In [20]:
np.median(x)

4.0

In [22]:
np.median(x,axis=1)

array([ 2.,  4., 90.])

In [23]:
np.median(x,axis=0)

array([2., 4., 6.])

In [24]:
np.var(x)

1474.888888888889

In [25]:
np.std(x)

38.4042821686448