In [1]:
pwd

'C:\\Users\\iibm\\Documents\\Bismillah 1st\\1st Day of Workshop'

In [2]:
print("workshop on python")

workshop on python


In [3]:
print('workshop on python')

workshop on python


In [6]:
print('a \'a\'')

a 'a'


In [7]:
print('''a 'alok' ''')

a 'alok'



In [10]:
print('''
data science
zhi
iibm''')


data science
zhi
iibm


# Arithmetic Operator

# Plus

In [11]:
2+5

7

In [12]:
6-3

3

In [13]:
6+4

10

In [14]:
5*2

10

In [16]:
2**2

4

In [15]:
10/2

5.0

In [17]:
4//2

2

In [19]:
4.2//2

2.0

In [20]:
2e2

200.0

In [21]:
5*5+8*2

41

In [22]:
(5+5)*2

20

In [23]:
x=10
x

10

In [24]:
x=20
x

20

In [25]:
print(x)

20


In [26]:
type(x)

int

In [27]:
print(type(x))

<class 'int'>


In [29]:
s= 'workshop'

In [30]:
s

'workshop'

In [31]:
print(s)

workshop


# Slicing and Indexind

#### s[start:end:step]

In [33]:
s[:]

'workshop'

In [34]:
s[: :]

'workshop'

In [35]:
s[5]

'h'

In [36]:
s[:5]

'works'

In [37]:
s[3:]

'kshop'

In [41]:
#print after two step
s[: : 2]

'wrso'

In [40]:
#reverse
s[::-1]

'pohskrow'

# Methods

In [44]:
#to capitalise
s.upper()

'WORKSHOP'

In [45]:
#for permanent change
s=s.upper()

In [46]:
s

'WORKSHOP'

In [48]:
#to small
s.lower()

'workshop'

# Split

In [52]:
'data'.split()

['data']

In [53]:
# to split by blank space
'A B C D E '.split()

['A', 'B', 'C', 'D', 'E']

In [56]:
#to split by condition that means it splits by and from c
'A B C D E '.split('C')

['A B ', ' D E ']

In [57]:
s.split('S')

['WORK', 'HOP']

# Print Properties

In [65]:
name= 'Virat '
run=100

In [68]:
#to concatenate
print(name + str( run))

Virat 100


# Formatting

In [75]:
print('this is a %s pen'%('ram'))

this is a ram pen


In [76]:
print('this is a %s pen %s'%('ram','abc'))

this is a ram pen abc


# Lists

In [77]:
My_list=['A B C D'.split()]

In [78]:
My_list

[['A', 'B', 'C', 'D']]

In [79]:
My_list='A B C D'.split()

In [80]:
My_list

['A', 'B', 'C', 'D']

In [81]:
My_list=['A',5,5.3]

In [82]:
My_list

['A', 5, 5.3]

In [84]:
type(My_list)

list

In [85]:
print(type(My_list))

<class 'list'>


# Slicing and Indexing in Lists

In [86]:
My_list[1]

5

In [87]:
My_list[0:2]

['A', 5]

In [88]:
My_list[0:3:1]

['A', 5, 5.3]

In [89]:
My_list[0:3:2]

['A', 5.3]

In [94]:
My_list[ : :-1]

[5.3, 5, 'A']

In [95]:
My_list*2

['A', 5, 5.3, 'A', 5, 5.3]

In [96]:
My_list=My_list+['a']

In [97]:
My_list

['A', 5, 5.3, 'a']

# List Method

In [98]:
l=[1,2,3,4,5]

In [99]:
l

[1, 2, 3, 4, 5]

In [100]:
l.append('A B C'.split())

In [101]:
l


[1, 2, 3, 4, 5, ['A', 'B', 'C']]

In [102]:
l.append('a')

In [103]:
l


[1, 2, 3, 4, 5, ['A', 'B', 'C'], 'a']

In [104]:
type(l)

list

In [105]:
print(type(l))

<class 'list'>


In [106]:
list1=[1,2,3,4,5,'A']

In [107]:
list1

[1, 2, 3, 4, 5, 'A']

In [108]:
list1.append('bishu')

In [109]:
list1

[1, 2, 3, 4, 5, 'A', 'bishu']

In [113]:
# to delete a list element
list1.pop(1)

3

In [114]:
list1

[1, 4, 5, 'A', 'bishu']

In [115]:
l1=[1,2,3]
l2=[4,5,6]
l3=[7,8,9]


In [116]:
#to concatenate lists
matrix=[l1,l2,l3]

In [117]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [118]:
type(matrix)

list

In [119]:
print(type(matrix))

<class 'list'>


In [122]:
matrix[1]

[4, 5, 6]

In [121]:
matrix[1][0]

4

In [123]:
len(matrix)

3

# Tuple

In [125]:
t1=(1,2,3)

In [126]:
t1

(1, 2, 3)

In [127]:
type(t1)

tuple

In [128]:
print(type(t1))

<class 'tuple'>


In [129]:
#no changes
t1[2]=4

TypeError: 'tuple' object does not support item assignment

In [130]:
list=[1,2,3]

In [131]:
list

[1, 2, 3]

In [136]:
#changible
list[2]=5

In [133]:
list

[1, 2, 5]

# Tuple slicing and indexing (Methods)

In [134]:
t1[1]

2

In [135]:
t1[-1]

3

In [137]:
# to indicate place
t1.index(2)

1

In [139]:
# value counting how many times is it written in tuple
t1.count(2)

1

# Dictionary

In [140]:
dic1={1:'a',2:'b',3:'c'}

In [141]:
dic1

{1: 'a', 2: 'b', 3: 'c'}

In [142]:
type(dic1)

dict

In [143]:
print(type(dic1))

<class 'dict'>


In [144]:
dic1[1]

'a'

In [145]:
dic1[2]

'b'

In [146]:
dic1[4]='ram'

In [147]:
dic1

{1: 'a', 2: 'b', 3: 'c', 4: 'ram'}

In [148]:
dic1[4]

'ram'

### Nested Dictionary

In [157]:
dic2={1: 'a', 2: 'b', 3: 'c', 4: 'ram','key1': {1:'apple',2:'hello',3:'cat'}}

In [158]:
dic2

{1: 'a', 2: 'b', 3: 'c', 4: 'ram', 'key1': {1: 'apple', 2: 'hello', 3: 'cat'}}

In [159]:
dic2['key1']

{1: 'apple', 2: 'hello', 3: 'cat'}

In [160]:
dic2['key1'][2]

'hello'

In [161]:
dic2['key1'][2][3]

'l'

# Dictionary Method

In [165]:
dic2.keys()

dict_keys([1, 2, 3, 4, 'key1'])

In [166]:
dic2.values()

dict_values(['a', 'b', 'c', 'ram', {1: 'apple', 2: 'hello', 3: 'cat'}])

In [167]:
dic2.items()

dict_items([(1, 'a'), (2, 'b'), (3, 'c'), (4, 'ram'), ('key1', {1: 'apple', 2: 'hello', 3: 'cat'})])

# Set 

### Unordered Collection

In [168]:
x=set()

In [169]:
x

set()

In [170]:
type(x)

set

In [171]:
print(type(x))

<class 'set'>


In [172]:
x.add(1)

In [173]:
x

{1}

In [174]:
list=[1,2,3,4,11,2,3,22,33]

In [176]:
list

[1, 2, 3, 4, 11, 2, 3, 22, 33]

In [177]:
set(list)

{1, 2, 3, 4, 11, 22, 33}

## Boolean

In [178]:
True

True

In [179]:
False

False

In [189]:
None

###### Question

Reassign 'hello' in this nested list to say 'goodbye' instead:
list3=[1,2,[3,4,'hello']]

In [184]:
l3=[1,2,[3,4,'hello']]

In [185]:
l3

[1, 2, [3, 4, 'hello']]

In [186]:
l3[2]

[3, 4, 'hello']

In [187]:
l3[2][2]='goodbye'

In [188]:
l3

[1, 2, [3, 4, 'goodbye']]

## Membership Operator

In [216]:
m='zhipatna'

In [217]:
m

'zhipatna'

In [218]:
'p' in m

True

In [219]:
't' not in m

False

In [220]:
x=100
y=100

In [221]:
x is y

True

In [222]:
x is not y

False

In [233]:
list1=[1,2,3]


In [234]:
list2=[1,2,3]

In [235]:
list1 is list2

False

In [236]:
list1 == list2

True

# Numerical Python

In [2]:
import numpy as np

In [239]:
x=[1,2,3,4,5]
x

[1, 2, 3, 4, 5]

In [240]:
type(x)

list

In [241]:
y= np.array(x)

In [242]:
type(y)

numpy.ndarray

In [243]:
x2=(1,2,3,'NEILIT',3.4)

In [244]:
np.array(x2)

array(['1', '2', '3', 'NEILIT', '3.4'], dtype='<U11')

# Line Space

In [245]:
np.linspace(start=0, stop=20, num=10, endpoint=False, retstep=True)

(array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]), 2.0)

In [246]:
np.linspace(start=0, stop=20, num=10, endpoint=True, retstep=True)

(array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
        11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ]),
 2.2222222222222223)

# Arange

In [247]:
np.arange(start=0, stop=50, step=5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [248]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [249]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [250]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3*3 Array

In [251]:
z=[[1,2,3],[5,4,6],[7,8,9]]

In [252]:
z

[[1, 2, 3], [5, 4, 6], [7, 8, 9]]

In [253]:
y=np.array(z)

In [254]:
y

array([[1, 2, 3],
       [5, 4, 6],
       [7, 8, 9]])

In [257]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [258]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [259]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Reshaping

In [267]:
x=np.array([0,1,2,3,4,5,6,7,8,9])

In [268]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Converting 5*2

In [269]:
x.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [270]:
x.reshape((1,10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [271]:
x.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [272]:
x.reshape((10,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [1]:
# 'cause of all the elements have to come lag with array
#x.reshape((3,3))

# Slicing

In [274]:
a= np.arange(10)

In [275]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [277]:
s=slice(2,7)

In [279]:
a[s]

array([2, 3, 4, 5, 6])

In [280]:
s1=slice(2,7,2)

In [281]:
a[s1]

array([2, 4, 6])

In [282]:
a[2:7]

array([2, 3, 4, 5, 6])

In [283]:
a[2:7:2]

array([2, 4, 6])

# Random Number Generation

In [284]:
np.random.rand(5)

array([0.54872454, 0.20858547, 0.84320666, 0.29563822, 0.09083147])

In [285]:
np.random.rand(5)

array([0.68682027, 0.1129315 , 0.93463933, 0.25480587, 0.56144507])

# Normal Distribution

In [286]:
np.random.randn(5,4)

array([[-0.17195033, -0.1321783 , -0.59881724,  0.55949905],
       [ 1.01639432,  0.10359364, -1.7629913 ,  0.51206225],
       [-2.17515197,  1.28782421,  0.27891024,  1.14228751],
       [-0.13415727, -0.79495571,  1.65406322, -0.63897044],
       [-0.24390525, -0.02325259, -0.84008367,  0.87388321]])

# Random integer

In [291]:
np.random.randint(low=0,high=100)

54

In [292]:
# Four Digit NUmber
np.random.randint(low=1000,high=9999)

9285

In [294]:
# for 10 array elements
np.random.randint(low=1000,high=9999,size=10)

array([3011, 5046, 3500, 9383, 2270, 9364, 8631, 6057, 4320, 1285])

# Seed

In [296]:
np.random.seed(23)
np.random.rand(4)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584])

In [297]:
np.random.seed(23)
np.random.rand(4)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584])

In [298]:
np.random.seed(23)
np.random.randint(low=0,high=100)

83

In [300]:
np.random.seed(23)
np.random.randint(low=0,high=100)

83

In [299]:
np.random.seed(23)
np.random.randint(low=1000,high=9999,size=10)

array([9787, 7175, 1347, 1039, 4674, 9857, 5019, 8174, 1049, 3507])

In [35]:
np.random.seed(23)
np.random.randint(low=1000,high=9999,size=10)

array([9787, 7175, 1347, 1039, 4674, 9857, 5019, 8174, 1049, 3507])

In [38]:
x=np.random.randint(low=1000,high=9999,size=10)
np.random.seed(23)
x

array([9787, 7175, 1347, 1039, 4674, 9857, 5019, 8174, 1049, 3507])

In [39]:
x=np.random.randint(low=1000,high=9999,size=10)
np.random.seed(23)
x

array([9787, 7175, 1347, 1039, 4674, 9857, 5019, 8174, 1049, 3507])