In [1]:
import numpy as np

# Brodcasting

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [4]:
list1=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
list1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
list1[1]/10

0.1

In [7]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [8]:
arr-1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [9]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [10]:
arr[arr>5]

array([6, 7, 8, 9])

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr1=arr[0:6]

In [13]:
arr1

array([0, 1, 2, 3, 4, 5])

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[:5]

array([0, 1, 2, 3, 4])

In [16]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [17]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr1[:]=555

In [19]:
arr1

array([555, 555, 555, 555, 555, 555])

In [20]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

# Copy of an Array

In [21]:
arr2 = arr.copy()

In [22]:
arr2

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

In [23]:
arr2[:]=1000

In [24]:
arr2

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [25]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

# Python list Vs Numpy Arrray

In [26]:
size = 1000
x = range(size)
y = range(size)

In [27]:
%%timeit
[x[i]*y[i] for i in range(size)]

230 µs ± 11 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [28]:
x1 = np.arange(size)
y1 = np.arange(size)

In [29]:
%%timeit
x1*y1

1.29 µs ± 32.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Insert

In [30]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
b1 = np.insert(b,1,[15,16,17],axis = 0)

In [32]:
np.insert(b,1,[15,16,17],axis = 1)

array([[ 1, 15,  2,  3],
       [ 4, 16,  5,  6],
       [ 7, 17,  8,  9]])

In [33]:
b1

array([[ 1,  2,  3],
       [15, 16, 17],
       [ 4,  5,  6],
       [ 7,  8,  9]])

# Matrix

In [34]:
x = np.matrix('1,2,3;4,5,6;7,8,9')
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [35]:
x[2,1] = -7
x

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7, -7,  9]])

In [36]:
#x[2,2] = -9
#x

In [37]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr[2,1] = -7

In [45]:
np.insert(arr,2,2)

array([ 1,  2,  2,  3,  4,  5,  6,  7, -7,  9])

In [49]:
x * x

matrix([[ 30,  -9,  42],
        [ 66,  -9,  96],
        [ 42, -84,  60]])

In [48]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 49, 81]])

In [50]:
arr @ arr


array([[ 30,  -9,  42],
       [ 66,  -9,  96],
       [ 42, -84,  60]])

# Storage in File

In [51]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [52]:
np.savetxt('a.txt',arr)

In [54]:
np.savetxt('a.txt',arr,delimiter = ',')

In [55]:
np.loadtxt('a.txt',delimiter = ',')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7., -7.,  9.]])

In [56]:
np.save('data.npy',arr)

In [57]:
np.load('data.npy')

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [59]:
a = np.arange(10)

In [60]:
np.savez('both.npz',arr,a)

In [61]:
z = np.load('both.npz')

In [62]:
z.files

['arr_0', 'arr_1']

In [63]:
z[z.files[1]]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
z[z.files[0]]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])